export const TEXT = {
  NOT_FOUND: "Ошибка 404. Нет такой страницы",
  LOADING: "Загрузка...",
  LEADERBOARD: {
    PLACE: "Место",
    PLAYER: "Игрок",
    SCORE: "Счет",
    TITLE: "Лучшие игроки",
    NO_LEADERS: "Лидеров пока нет. Отличная возможность стать первым!",
    CALL_TO_ACTION: "Установить новый рекорд",
    ERROR: "Не удалось загрузить список лидеров",
  },
  SETTINGS: {
    TITLE: "Профиль",
    CHANGE_AVATAR: "Изменить фото профиля",
    FIRST_NAME: "Введите имя",
    SECOND_NAME: "Введите фамилию",
    DISPLAY_NAME: "Введите певдоним",
    EMAIL: "Введите адрес электронной почты",
    PHONE: "Введите номер мобильного телефона",
    CURRENT_PASSWORD: "Действующий пароль",
    NEW_PASSWORD: "Введите новый пароль",
    NEW_PASSWORD_CONFIRM: "Повторите новый пароль",
    SUBMIT: "Сохранить",
    LOGOUT: "Выйти",
  },
  SIGNIN: {
    TITLE: "Вход",
    LOGIN: "Введите логин",
    PASSWORD: "Введите пароль",
    BUTTON_SIGNIN: "Войти",
    BUTTON_SIGNUP: "Зарегистрироваться",
    BUTTON_SIGNIN_YANDEX: "Войти через Яндекс",
    BUTTON_PLAY: "Играть без авторизации",
  },
  SIGNUP: {
    TITLE: "Регистрация",
    FIRST_NAME: "Имя",
    SECOND_NAME: "Фамилия",
    LOGIN: "Придумайте логин",
    EMAIL: "Адрес электронной почты",
    PASSWORD: "Придумайте пароль",
    PASSWORD_CONFIRM: "Повторите пароль",
    PHONE: "Номер мобильного телефона",
    SUBMIT: "Зарегистрироваться",
    SIGNIN: "Войти с паролем",
  },
  GAME: {
    RESTART: "Пробел, чтобы начать сначала",
    ERROR: "Что-то пошло не так",
    ERROR_POINTER_LOCK_API: "Браузер не поддерживает pointer-lock",
  },
  SERVER: {
    SERVER_RUNNING_MESSAGE: "SSR running on port",
    ERROR_NO_APP_BUNDLE: "Сan't find compiled app bundle",
  },
} as const;
